name             'sensu_client'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures sensu_client'
long_description 'Installs/Configures sensu_client'
version          '0.1.0'

depends 'apt'
depends 'conjur'
depends 'sensu'
